version: '3.8'
services:
  springboot-app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "9090:9090"

  react-app:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_ENV=production
      - REACT_APP_PROXY=https://springboot-app:9090
