services:
  springboot-app:
    build:
      args:
        - VERTEX_AI_SERVICE_KEY_FILENAME=${VERTEX_AI_SERVICE_KEY_FILENAME}
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "9090:9090"
    env_file:
      - .env

  react-app:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    env_file:
      - .env

  mysql-server:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./database/db-data:/var/lib/mysql
    env_file:
      - .env
