version: '3.8'
services:
  springboot-app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - MYSQL_URL=${MYSQL_URL}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}

  react-app:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_ENV=${REACT_APP_ENV}
      - REACT_APP_PROXY=${REACT_APP_PROXY}

  mysql-server:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./database/db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
