version: '3.8'
services:
  springboot-app:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "9090:9090"
    volumes:
      - ./server/src:/app/src # 이미지 **빌드**시에만 코드를 옮기고, 여기서 정의된 volume의 코드는 컨테이너를 올릴때 그 위로 오버레이 됨.
      - ./server/build.gradle:/app/build.gradle
      - ./server/config:/app/config
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  react-app:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - /app/node_modules # node_modules는 컨테이너 내부에서 관리
    ports:
      - "3000:3000" # node 서버의 기본 포트를 사용
    environment:
      - NODE_ENV=development